# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-13 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fOn', '0002_auto_20170613_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unlike',
            name='unliked_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
