# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fOn', '0005_auto_20170614_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='userlike',
        ),
        migrations.AddField(
            model_name='like',
            name='userlike',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='userunlike',
        ),
        migrations.AddField(
            model_name='unlike',
            name='userunlike',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
