# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fOn', '0006_auto_20170614_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='userlike',
        ),
        migrations.AddField(
            model_name='like',
            name='userlike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='userunlike',
        ),
        migrations.AddField(
            model_name='unlike',
            name='userunlike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
