# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fOn', '0007_auto_20170614_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_commneted',
            new_name='user_commented',
        ),
    ]
