# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fOn', '0008_auto_20170620_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
