# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fOn', '0013_auto_20180308_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
